/data-analytics-dashboard-portfolio
    /finance
        /dashboard1
        /dashboard2
        README.md
    /health
        /dashboard1
        /dashboard2
        README.md
    /other
        /dashboard1
        /dashboard2
        README.md
    README.md
